name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build ROS package
      uses: jspricke/ros-deb-builder-action@main
      with:
        ROS_DISTRO: humble
        DEB_DISTRO: jammy
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
