name: ROS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        sudo apt install -y python3-colcon-common-extensions python3-rosdep
        sudo rosdep init
        rosdep update
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
        source ~/.bashrc

    - name: Setup workspace
      run: |
        mkdir -p ~/colcon_ws/src
        mv ./* ~/colcon_ws/src/

    - name: Install dependencies
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/colcon_ws
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/colcon_ws
        colcon build
